### ISSUE TITLE
Message parameter on assert_not_empty

### ISSUE THREAD

**Issue by bguerout** [torokmark/assert.sh#1]
Hello,

`assert_not_empty` uses third parameter as message but second one seems not used (https://github.com/torokmark/assert.sh/blob/master/assert.sh#L188)

This prevent `assert_not_empty` function to be written as follow
`assert_not_empty "my string" "This is the message"`

And must be written with a second empty parameter, exactly like `assert_not_eq`
`assert_not_empty "my string" "" "This is the message"`

**Comment by torokmark** [comment]
Hi Benoit,

Thank you for the remark, fixed it, now the second param is the message, no empty string is needed to fill up the space.

Regards,
Mark
